services:
  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend/
    ports:
      - "8000:8000"
    restart: always
    networks:
      compslidesnetwork:
        ipv4_address: 172.28.2.1
    
  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile.dev
    command: npx vite dev --host
    volumes:
      - ./frontend/:/frontend/
    ports:
      - "8001:5173"
    depends_on:
      - backend
    restart: always
    networks:
      compslidesnetwork:
        ipv4_address: 172.28.2.2

networks:
  compslidesnetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
