# this dockerfile is for the backend deployed on railway
# it basically only adds the script folder to the backend Docker image
# because normally it is in the outside directory

FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    libmariadb-dev \
    gcc \
    build-essential \
    libssl-dev \
    pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY backend /app/
COPY scripts /scripts/

RUN mkdir -p /app/public
RUN chmod -R 755 /app/public

CMD ["sh", "-c", "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python3 -m gunicorn backend.wsgi:application --bind 0.0.0.0:8000"]