services:
  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend/
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      mynetwork:
        ipv4_address: 172.28.2.1
    
  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile.dev
    command: npx vite dev --host
    volumes:
      - ./frontend/:/frontend/
    ports:
      - "8001:5173"
    depends_on:
      - backend
    restart: always
    networks:
      mynetwork:
        ipv4_address: 172.28.2.2

  db:
    image: mysql:8.0
    env_file: ./backend/backend/.env
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      mynetwork:
        ipv4_address: 172.28.2.3

networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
