# Generated by Django 4.2.3 on 2023-07-27 17:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_user_name_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-points"]},
        ),
        migrations.AddField(
            model_name="slide",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slide",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="slide",
            name="hits",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="slide",
            name="misses",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="slide",
            name="tips_used",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SlideImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tip_index", models.IntegerField()),
                ("image", models.ImageField(default="default_slide.jpg", upload_to="")),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "slide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.slide"
                    ),
                ),
            ],
        ),
    ]
