# Generated by Django 4.2.3 on 2023-08-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_user_options_slide_created_slide_updated_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="slide",
            old_name="tips_amount",
            new_name="hints_amount",
        ),
        migrations.RenameField(
            model_name="slide",
            old_name="tips_used",
            new_name="hints_used",
        ),
        migrations.RenameField(
            model_name="slideimages",
            old_name="tip_index",
            new_name="hint_index",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="tips_used",
            new_name="hints_used",
        ),
    ]
