# Generated by Django 4.2.3 on 2023-08-08 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_rename_slideimages_slideimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="hints_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="hits",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="misses",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slides_left", models.IntegerField(default=10)),
                ("hits", models.IntegerField(default=0)),
                ("misses", models.IntegerField(default=0)),
                ("hints_used", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "current_hint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.slideimage",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
