# Generated by Django 5.0.1 on 2024-01-10 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_sliderun_has_hit_alter_sliderun_has_missed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderun',
            old_name='alternatives',
            new_name='slide_alternatives',
        ),
    ]
