# Generated by Django 5.0.1 on 2024-01-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_alternatives_sliderun_slide_alternatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
