# Generated by Django 5.0.1 on 2024-01-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_user_message_alter_run_slides_left_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='id_user',
            new_name='user',
        ),
    ]
