# Generated by Django 5.0.1 on 2024-01-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_id_user_run_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='max_points_per_slide_run',
        ),
        migrations.RemoveField(
            model_name='config',
            name='max_slides_per_run',
        ),
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(default='a', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='value',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
