# Generated by Django 4.2.3 on 2023-08-08 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_rename_tips_amount_slide_hints_amount_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SlideImages",
            new_name="SlideImage",
        ),
    ]
