# Generated by Django 4.2.3 on 2023-10-29 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_user_hints_used_alter_user_hits_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideimage",
            name="image",
            field=models.ImageField(default="default_slide.jpg", upload_to="static/"),
        ),
        migrations.CreateModel(
            name="SlideRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_hit", models.BooleanField(default=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "original_slide",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.slide",
                    ),
                ),
                (
                    "run_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.run",
                    ),
                ),
            ],
        ),
    ]
