# Generated by Django 5.0.1 on 2024-01-09 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_slideimage_image_sliderun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-total_points']},
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='hints_used',
            new_name='total_hints_used',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='hits',
            new_name='total_hits',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='misses',
            new_name='total_misses',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='hints_used',
            new_name='total_hints_used',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='hits',
            new_name='total_hits',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='misses',
            new_name='total_misses',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='points',
            new_name='total_points',
        ),
        migrations.RemoveField(
            model_name='run',
            name='hints_used',
        ),
        migrations.RemoveField(
            model_name='run',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='run',
            name='misses',
        ),
        migrations.RemoveField(
            model_name='run',
            name='points',
        ),
        migrations.AddField(
            model_name='sliderun',
            name='alternatives',
            field=models.ManyToManyField(related_name='alternatives', to='base.slide'),
        ),
        migrations.AddField(
            model_name='sliderun',
            name='has_missed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sliderun',
            name='hints_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sliderun',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sliderun',
            name='has_hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sliderun',
            name='original_slide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.slide'),
        ),
        migrations.AlterField(
            model_name='sliderun',
            name='run_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.run'),
        ),
    ]
