# Generated by Django 5.0.1 on 2024-01-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderun',
            name='has_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sliderun',
            name='has_missed',
            field=models.BooleanField(default=False),
        ),
    ]
