# Generated by Django 5.0.1 on 2024-01-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_run_total_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_points_per_slide_run', models.IntegerField(default=5)),
                ('max_slides_per_run', models.IntegerField(default=10)),
            ],
        ),
    ]
