# Generated by Django 5.0.1 on 2025-06-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_config_max_points_per_slide_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='total_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sliderun',
            name='points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_points',
            field=models.FloatField(default=0.0),
        ),
    ]
