# Generated by Django 5.0.1 on 2025-06-25 23:47

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_run_total_points_alter_sliderun_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Add Multiple Slides at once',
            },
        ),
        migrations.CreateModel(
            name='ZipSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Add a .zip file with all slides',
            },
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='hint_index',
            field=models.IntegerField(help_text='Index of the hint, starting from 0'),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='image',
            field=models.ImageField(default='default_slide.jpg', upload_to=base.models.HashedDirectory('static/')),
        ),
    ]
