# Generated by Django 5.0.1 on 2025-06-26 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_multipleslides_zipslides_alter_slideimage_hint_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='current_hint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.slideimage'),
        ),
    ]
