# Generated by Django 5.0.2 on 2026-02-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_run_current_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideimage',
            name='times_guessed_right',
            field=models.IntegerField(default=0, help_text='Number of times this hint was the one shown when the user guessed correctly'),
        ),
        migrations.AddField(
            model_name='slideimage',
            name='times_guessed_wrong',
            field=models.IntegerField(default=0, help_text='Number of times this hint was the one shown when the user guessed incorrectly'),
        ),
        migrations.AddField(
            model_name='slideimage',
            name='times_skipped',
            field=models.IntegerField(default=0, help_text='Number of times this hint was skipped'),
        ),
    ]
