# Generated by Django 5.2.16 on 2026-09-22 20:21

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_slideimage_times_guessed_right_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_index', models.IntegerField(help_text='Index of the hint, starting from 0')),
                ('image', models.ImageField(default='default_frame.jpg', upload_to=base.models.HashedDirectory('static/'))),
                ('times_skipped', models.IntegerField(default=0, help_text='Number of times this hint was skipped')),
                ('times_guessed_right', models.IntegerField(default=0, help_text='Number of times this hint was the one shown when the user guessed correctly')),
                ('times_guessed_wrong', models.IntegerField(default=0, help_text='Number of times this hint was the one shown when the user guessed incorrectly')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('director', models.CharField(max_length=200)),
                ('hints_amount', models.IntegerField()),
                ('total_hits', models.IntegerField(default=0)),
                ('total_misses', models.IntegerField(default=0)),
                ('total_hints_used', models.IntegerField(default=0)),
                ('difficulty_level', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_hit', models.BooleanField(default=False)),
                ('has_missed', models.BooleanField(default=False)),
                ('hints_used', models.IntegerField(default=0)),
                ('points', models.FloatField(default=0.0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('movie_alternatives', models.ManyToManyField(related_name='alternatives', to='base.movie')),
                ('original_movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='MultipleSlides',
        ),
        migrations.RemoveField(
            model_name='sliderun',
            name='slide_alternatives',
        ),
        migrations.RemoveField(
            model_name='sliderun',
            name='original_slide',
        ),
        migrations.RemoveField(
            model_name='slideimage',
            name='slide',
        ),
        migrations.RemoveField(
            model_name='sliderun',
            name='run_id',
        ),
        migrations.DeleteModel(
            name='ZipSlides',
        ),
        migrations.RenameField(
            model_name='run',
            old_name='slides_left',
            new_name='movies_left',
        ),
        migrations.AlterField(
            model_name='run',
            name='current_hint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.frame'),
        ),
    ]
