# Generated by Django 5.2.16 on 2026-09-22 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_frame_movie_movierun_delete_multipleslides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierun',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.run'),
        ),
    ]
